language: node_js
node_js:
  - "10"
sudo: required

cache:
  directories:
    - ~/.cache/nodejs
    - ~/.cache/yarn
    - ~/.cache/Cypress

install:
  - yarn install --frozen-lockfile
  - yarn cypress install
  - yarn cypress verify
  - yarn add dlx wait-on
  - yarn add dlx @testing-library/cypress
script:
  - yarn install
  - yarn build
  - yarn add serve
  - yarn serve & yarn wait-on http://localhost:3000
  - yarn cypress run