language: node_js
node_js:
  - "10"
sudo: required

cache:
  directories:
    - ./.yarn/cache

install:
  - yarn install --frozen-lockfile
  - yarn cypress install
  - yarn cypress verify
  - yarn add dlx wait-on
script:
  - yarn install
  - yarn build
  - yarn add serve
  - yarn serve & yarn wait-on http://localhost:3000
  - yarn cypress run