version: '3.7'

services:
  webapp:
    build:
      context: ./
      target: app
    image: webapp-image
  cypress:
    build:
      context: ./
      target: test-runner
    image: cypress-test-runner
    depends_on:
      - webapp
    environment:
      - CYPRESS_baseUrl=http://webapp:5000
      - BASE_IMAGE=webapp-image
    working_dir: /app
