version: '3.7'

services:
  webapp:
    build:
      context: ./
      target: app
    image: webapp-image
  nginx:
    build:
      context: ./
        target: nginx

    image: nginx
    tty: true
    ports:
        - 8080:80
    depends_on:
        - webapp
  cypress:
    build:
      context: ./
      target: test-runner
    image: cypress-test-runner
    depends_on:
      - webapp
    environment:
      - CYPRESS_baseUrl=http://nginx:80
      - BASE_IMAGE=webapp-image
    working_dir: /app
