services:
  web:
    build:
      context: ./
      target: builder
    container_name: user_tracker_project
    tty: true
    ports:
      - 5000:5000
    command: serve -s build

  cypress:
    ipc: host
    build:
      context: ./
      target: test-runner
    container_name: cypress_test_runner
    image: 'cypress_test_runner'
    tty: true
    ports:
    - 3000:3000
    depends_on:
      - web
    environment:
    - CYPRESS_BASE_URL=http://web:5000
