version: '3.7'

services:
  builder:
    build:
      context: ./
      target: builder
    image: builder-image
  nginx:
    build:
      context: ./
      target: nginx
    image: nginx
    ports:
      - 3000:80
    depends_on:
      - builder
  cypress:
    build:
      context: ./
      target: test-runner
    image: cypress-test-runner
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=http://nginx:80
      - BASE_IMAGE=builder-image
    working_dir: /app
